import os


CURRENT_DIRECTORY = os.getcwd() + "/app"
DATA_DIR = CURRENT_DIRECTORY + "/data"

# SERVER DATA
SERVICE_URL = "http://127.0.0.1:8000"
PROJECTS_BASE_URL = SERVICE_URL + "/products"
CARDS_BASE_URL = SERVICE_URL + "/cards"
LOGIN_URL = SERVICE_URL + "/login"
SIGNUP_URL = SERVICE_URL + "/users"
