---
name: "tagged-release"

on:
  push:
    branch:
      - "main"
    tags:
      - "v*"

jobs:
  tagged-release:
    permissions: write-all
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true

    name: Run latest-tag
    uses: EndBug/latest-tag@latest
    with:
      # You can change the name of the tag or branch with this input.
      # Default: 'latest'
      ref: 'latest'
